### ISSUE TITLE
Multiple bidding algorithms

### ISSUE THREAD

**Issue by taymonbeal** [google/fledge-shim#20]
Currently, the only supported bidding algorithm is "bid a static price associated with the creative". Once others are suggested, we will need a way to allow bidders to choose between them. This will be the FLEDGE `bidding_logic_url` parameter, except that it will be a URI of the form `fledge-shim:algorithm-name`.

**Comment by jeffkaufman** [comment]
You'll still need `bidding_logic_url`, to provide `report_win`, so I think this needs to be a separate parameter?

**Comment by taymonbeal** [comment]
New plan is to just allow an arbitrary allowlisted URL in `biddingLogicUrl` instead of bundling any logic.
