### ISSUE TITLE
Multiple scoring algorithms

### ISSUE THREAD

**Issue by taymonbeal** [google/fledge-shim#21]
Currently, the only supported scoring algorithm is "pass through the bid verbatim". Once others are suggested, we will need a way to allow sellers to choose between them. This will be the FLEDGE `decision_logic_url` parameter, except that it will be a URI of the form `fledge-shim:algorithm-name`.

**Comment by jeffkaufman** [comment]
Same issue as https://github.com/google/fledge-shim/issues/20#issuecomment-827142641

**Comment by taymonbeal** [comment]
New plan is to just allow an arbitrary allowlisted URL in `decisionLogicUrl` instead of bundling any logic.
